httpd:
  env_file:
    - ./httpd.env
  hostname: httpd-demo-wp
  image: alterway/httpd:2.4
  links:
  - php:phpfpm
  ports:
  - 80:80
  volumes_from:
  - sources
mysql:
  env_file:
    - ./mysql.env
  image: alterway/mysql:5.6
  volumes:
  - /var/lib/mysql
php:
  env_file:
    - ./php.env
    - ./wordpress.env
  hostname: php-demo-wp
  image: alterway/php:5.4-fpm
  links:
  - mysql:db
  volumes_from:
  - sources
sources:
  image: www-data
  volumes:
  - ${APP_PATH}:/var/www
